In [1]:
import pandas as pd
import numpy as np

In [164]:
df = pd.read_csv('train.csv')

In [165]:
df.shape

(550068, 12)

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 12 columns):
User_ID                       550068 non-null int64
Product_ID                    550068 non-null object
Gender                        550068 non-null object
Age                           550068 non-null object
Occupation                    550068 non-null int64
City_Category                 550068 non-null object
Stay_In_Current_City_Years    550068 non-null object
Marital_Status                550068 non-null int64
Product_Category_1            550068 non-null int64
Product_Category_2            376430 non-null float64
Product_Category_3            166821 non-null float64
Purchase                      550068 non-null int64
dtypes: float64(2), int64(5), object(5)
memory usage: 50.4+ MB


In [167]:
df.isnull().sum()

User_ID                            0
Product_ID                         0
Gender                             0
Age                                0
Occupation                         0
City_Category                      0
Stay_In_Current_City_Years         0
Marital_Status                     0
Product_Category_1                 0
Product_Category_2            173638
Product_Category_3            383247
Purchase                           0
dtype: int64

In [137]:
df.head()

User_ID Product_ID Gender   Age  Occupation City_Category  \
0  1000001  P00069042      F  0-17          10             A   
1  1000001  P00248942      F  0-17          10             A   
2  1000001  P00087842      F  0-17          10             A   
3  1000001  P00085442      F  0-17          10             A   
4  1000002  P00285442      M   55+          16             C   

  Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
0                          2               0                   3   
1                          2               0                   1   
2                          2               0                  12   
3                          2               0                  12   
4                         4+               0                   8   

   Product_Category_2  Product_Category_3  Purchase  
0                 NaN                 NaN      8370  
1                 6.0                14.0     15200  
2                 NaN                 NaN      1422  
3                14.0                 NaN      1057  
4                 NaN                 NaN      7969

In [ ]:
df['User_ID'].unique().shape

In [ ]:
df['Product_ID'].unique().shape

In [ ]:
df['Age'].unique()

In [138]:
df['Product_Category_2'].fillna(0, inplace = True)

In [139]:
df['Product_Category_3'].fillna(0, inplace = True)

In [45]:
from sklearn.preprocessing import LabelEncoder

In [140]:
X = df.drop(['Purchase','User_ID', 'Product_ID'], axis = 1)

In [141]:
X.head()

Gender   Age  Occupation City_Category Stay_In_Current_City_Years  \
0      F  0-17          10             A                          2   
1      F  0-17          10             A                          2   
2      F  0-17          10             A                          2   
3      F  0-17          10             A                          2   
4      M   55+          16             C                         4+   

   Marital_Status  Product_Category_1  Product_Category_2  Product_Category_3  
0               0                   3                 0.0                 0.0  
1               0                   1                 6.0                14.0  
2               0                  12                 0.0                 0.0  
3               0                  12                14.0                 0.0  
4               0                   8                 0.0                 0.0

In [168]:
X_t = X.drop(['Gender', 'Age','Occupation','City_Category','Stay_In_Current_City_Years'], axis = 1)

In [169]:
X2 = X.drop(['Marital_Status','Product_Category_1','Product_Category_2', 'Product_Category_3'], axis = 1)

In [170]:
X_t.head()

Marital_Status  Product_Category_1  Product_Category_2  Product_Category_3
0               0                   3                 0.0                 0.0
1               0                   1                 6.0                14.0
2               0                  12                 0.0                 0.0
3               0                  12                14.0                 0.0
4               0                   8                 0.0                 0.0

In [171]:
X2.head()

Gender   Age  Occupation City_Category Stay_In_Current_City_Years
0      F  0-17          10             A                          2
1      F  0-17          10             A                          2
2      F  0-17          10             A                          2
3      F  0-17          10             A                          2
4      M   55+          16             C                         4+

In [144]:
X_dash = X2.apply(LabelEncoder().fit_transform).join(X_t)

In [172]:
X_dash.head()

Gender  Age  Occupation  City_Category  Stay_In_Current_City_Years  \
0       0    0          10              0                           2   
1       0    0          10              0                           2   
2       0    0          10              0                           2   
3       0    0          10              0                           2   
4       1    6          16              2                           4   

   Marital_Status  Product_Category_1  Product_Category_2  Product_Category_3  
0               0                   3                 0.0                 0.0  
1               0                   1                 6.0                14.0  
2               0                  12                 0.0                 0.0  
3               0                  12                14.0                 0.0  
4               0                   8                 0.0                 0.0

In [145]:
y = df.Purchase

In [146]:
X_dash.shape, y.shape

((550068, 9), (550068,))

In [ ]:
X_dash.shape

In [ ]:
y.shape

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge #lasso and ridge gave same output  and both utter useless
from sklearn.gaussian_process import GaussianProcessRegressor #memory error
from sklearn.neighbors import KNeighborsRegressor

from sklearn.cross_decomposition import PLSRegression # worst output
from sklearn.svm import SVR

from sklearn import metrics

In [ ]:
X_dash

In [ ]:
X_dash.head()

In [173]:
X_dash.shape, y.shape

((550068, 9), (550068,))

In [161]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_dash, y, random_state = 1)

In [148]:
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

In [163]:
model = GradientBoostingRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print (np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
# 3026.90938765 best with GradientBoostingRegressor with -999 as fillna
# 2979.42326826 best with GradientBoostingRegressor with 0 as fillna with scaling and without scaling

2979.42326826


In [150]:
model.fit(X_dash, y)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='ls', max_depth=3, max_features=None,
             max_leaf_nodes=None, min_impurity_split=1e-07,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=100,
             presort='auto', random_state=None, subsample=1.0, verbose=0,
             warm_start=False)

In [151]:
test = pd.read_csv('test.csv')

In [ ]:
test.head()

In [152]:
test_X = test.drop(['User_ID', 'Product_ID'], axis = 1)

In [153]:
test_X_t = test_X.drop(['Gender', 'Age','Occupation','City_Category','Stay_In_Current_City_Years'], axis = 1)
test_X2 = test_X.drop(['Marital_Status','Product_Category_1','Product_Category_2', 'Product_Category_3'], axis = 1)
test_X_dash = test_X2.apply(LabelEncoder().fit_transform).join(test_X_t)

In [154]:
test_X_dash['Product_Category_2'].fillna(0, inplace = True)
test_X_dash['Product_Category_3'].fillna(0, inplace = True)

In [155]:
test_X_dash.head()

Gender  Age  Occupation  City_Category  Stay_In_Current_City_Years  \
0       1    4           7              1                           2   
1       1    2          17              2                           0   
2       0    3           1              1                           4   
3       0    3           1              1                           4   
4       0    2           1              2                           1   

   Marital_Status  Product_Category_1  Product_Category_2  Product_Category_3  
0               1                   1                11.0                 0.0  
1               0                   3                 5.0                 0.0  
2               1                   5                14.0                 0.0  
3               1                   4                 9.0                 0.0  
4               0                   4                 5.0                12.0

In [156]:
test_y_pred = model.predict(test_X_dash)

In [157]:
test_y_pred

array([ 13224.07318579,  10000.79744822,   6070.46459713, ...,
        13067.92311891,  18922.7635395 ,   2582.42277054])

In [22]:
test_output = test[['User_ID', 'Product_ID']]

In [158]:
test_output['Purchase'] = test_y_pred

In [ ]:
test_output.head()

In [159]:
test_output.to_csv('gradientboostensemblescalingwith0.csv')

In [101]:
X_dash['Purchase'] = y

In [102]:
X_dash.to_csv('X.csv',index = False)
y.to_csv('y.csv', index = False)
test_X_dash.to_csv('test_X_dash.csv', index = False)

Keras version

In [26]:
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.cross_validation import cross_val_score, KFold

In [27]:
# define base model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(13, input_dim=9, kernel_initializer='normal', activation='relu'))
    model.add(Dense(1, kernel_initializer='normal'))
    # Compile model
    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

In [37]:
seed = 7
np.random.seed(seed)

estimator = KerasRegressor(build_fn=baseline_model, nb_epoch=100, batch_size=5,verbose=0)

# kfold = KFold(n_splits=10, random_state=seed)
# results = cross_val_score(estimator, X_dash, y, cv=kfold)
# print("Results: %.2f (%.2f) MSE" % (results.mean(), results.std()))

In [29]:
estimator.fit(X_train,y_train)
y_pred = estimator.predict(X_test)

print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

4344.69865067


In [30]:
y_pred

array([  7565.55517578,   9885.00878906,   6665.25634766, ...,
         9195.0546875 ,   7203.16796875,  10925.49511719], dtype=float32)

In [121]:
estimator.fit(X.as_matrix(), y)

In [128]:
np.array([0,2,1,2,1,0,4,5.0,12.0]).reshape(1,-1).shape

(1, 9)

In [129]:
y_pred = estimator.predict(np.array([0,2,1,2,1,0,4,5.0,12.0]).reshape(1,-1))

In [134]:
estimator.predict(test_X.as_matrix())

array([ nan,  nan,  nan, ...,  nan,  nan,  nan], dtype=float32)

In [132]:
X_test.shape

(137517, 9)

In [130]:
y_pred

array(nan, dtype=float32)

In [116]:
X.shape, y.shape

((550068, 9), (550068,))

In [103]:
X = pd.read_csv('X.csv')
test_X = pd.read_csv('test_X_dash.csv')

In [112]:
X.shape

(550068, 9)

In [162]:
X_train

Gender  Age  Occupation  City_Category  Stay_In_Current_City_Years  \
413828       1    3          17              2                           3   
359829       1    1           4              1                           1   
325720       1    3          20              0                           0   
461095       1    3           2              1                           1   
325306       0    2          20              1                           4   
339871       1    5           1              2                           1   
320772       0    3          15              0                           1   
541995       0    1           2              0                           1   
294667       0    2          14              1                           4   
143889       1    6          13              2                           1   
83586        1    2          15              0                           1   
490350       1    2          11              2                           4   
142558       0    2          14              1                           4   
220066       1    2           5              1                           1   
226436       0    2           1              2                           1   
212105       1    2           1              0                           1   
521264       1    3           1              2                           3   
278532       1    2           0              1                           4   
516449       1    2          20              0                           1   
470284       1    1           4              1                           1   
146481       1    2           0              2                           1   
48171        0    2           7              0                           1   
123957       0    2          20              0                           1   
212678       1    3          12              1                           3   
300103       1    2           7              1                           1   
383206       1    4           0              2                           3   
207851       1    2           4              1                           3   
65806        1    2           7              2                           1   
199445       1    2           7              1                           1   
408837       0    3          17              2                           4   
...        ...  ...         ...            ...                         ...   
369977       1    4          17              1                           2   
117565       0    2          20              2                           2   
99335        0    2           7              2                           4   
296022       1    5           1              2                           1   
444256       1    6           1              0                           4   
26103        1    3          12              0                           1   
148209       1    2          16              0                           3   
412649       0    4           1              2                           0   
294103       1    1           1              1                           3   
246322       0    2           7              1                           4   
188317       1    2           2              0                           0   
365212       1    1          19              2                           4   
401660       1    2          20              2                           1   
457611       1    1           4              0                           3   
176485       1    1          12              1                           4   
21758        1    1          20              0                           1   
513300       1    2          15              1                           3   
167302       0    2          12              0                           4   
293372       1    3           7              1                           2   
436973       1    5           

In [106]:
y = X['Purchase']

In [107]:
y.shape

(550068,)

In [108]:
X.drop('Purchase', axis =1, inplace = True)

In [109]:
X.shape

(550068, 9)

In [118]:
test_X.shape

(233599, 9)

In [115]:
X.as_matrix()

array([[   0.,    0.,   10., ...,    3., -999., -999.],
       [   0.,    0.,   10., ...,    1.,    6.,   14.],
       [   0.,    0.,   10., ...,   12., -999., -999.],
       ..., 
       [   0.,    2.,   15., ...,   20., -999., -999.],
       [   0.,    6.,    1., ...,   20., -999., -999.],
       [   0.,    4.,    0., ...,   20., -999., -999.]])

In [133]:
test_X.isnull().sum()

Gender                        0
Age                           0
Occupation                    0
City_Category                 0
Stay_In_Current_City_Years    0
Marital_Status                0
Product_Category_1            0
Product_Category_2            0
Product_Category_3            0
dtype: int64